# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d35f0979b0a19b6bc47f221a28a1b13c8db1083ab830a2750694daa165bd05d3dece31be04077bd6f30a81866e996e517cb5d8aa9c92024d8e4c0a7d7f9e839

test:
  secret_key_base: 10ec827ba3c78a0d3aa068b589651b176002eac286c0c249f797a014ab74029f95c0725e511bfcdda7e4ba23f280e2111170feae397f73e9ee484a4a051fb7a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
